# In case the platform does NOT support this type of sensors
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y   +=  accel.o accel_factory.o

obj-$(CONFIG_MTK_MXC622X)   +=  mxc622x/
